### ISSUE TITLE
Update documentation to be more obvious

### ISSUE THREAD

**Issue by lemonlambda** [jomala/bevy_screen_diags#21]
Update the documentation here to make it more clear:
https://github.com/jomala/bevy_screen_diags/blob/master/src/lib.rs#L22-L26

Update the documentation here to make more of a distinction between the other type: https://github.com/jomala/bevy_screen_diags/blob/master/src/lib.rs#L38-L41

**Comment by jomala** [comment]
Does https://github.com/jomala/bevy_screen_diags/pull/23 cover this, @LemonjamesD ?
