### ISSUE TITLE
Feature: User-configurable options

### ISSUE THREAD

**Issue by rchar-star** [jomala/bevy_screen_diags#8]
As a user of this crate, it would be really nice to have control over (at a minimum) the font path, font size, text color, and update interval of the timer.

The Bevy way to do this seems to be using a Resource to control these values. This feature could be implemented in a backwards-compatible way by making use of a Default impl for the Resource struct that end-users can simply override. Would need some docs updates and maybe an example of changing these values.

I'm happy to work on this - feel free to assign me to it (if that's possible?).

**Comment by jomala** [comment]
The resource and the marked Text object can now (in 0.4.0 for Becy 0.7) both be tampered with to your hearts content. Anything more complex, it's probably worth just reimplementing this in your app, rather than extending the crate, but let me know if you have any suggestions.

**Comment by lemonlambda** [comment]
> As a user of this crate, it would be really nice to have control over (at a minimum) the font path, font size, text color, and update interval of the timer.
> 
> The Bevy way to do this seems to be using a Resource to control these values. This feature could be implemented in a backwards-compatible way by making use of a Default impl for the Resource struct that end-users can simply override. Would need some docs updates and maybe an example of changing these values.
> 
> I'm happy to work on this - feel free to assign me to it (if that's possible?).

I'm thinking of extending this by adding resources that control this because it would be more ergonomic than the current way of doing it

**Comment by jomala** [comment]
I've added a PR (https://github.com/jomala/bevy_screen_diags/pull/24) to show that it's not difficult to configure everything about the text. Think there are gains to be had by adding a big config block, @LemonjamesD ? I don't think so currently.

**Comment by lemonlambda** [comment]
> I've added a PR (#24) to show that it's not difficult to configure everything about the text. Think there are gains to be had by adding a big config block, @LemonjamesD ? I don't think so currently.

I think it would be nice but it's not that hard to do so in the current method.
