### ISSUE TITLE
Feature: A more ergonomic enable/disable API

### ISSUE THREAD

**Issue by rchar-star** [jomala/bevy_screen_diags#9]
It's a little inconvenient (and not particularly intuitive) to control whether or not the overlay is disabled via pausing/unpausing a timer.

I propose enabling & disabling could be handled via a boolean within either a Resource or a Component struct - users would mutably query this, and set the boolean to `true` to display the overlay, or `false` to hide it. This would also greatly simplify the internal logic within the update system - basically entailing a complete re-write.

**This would be a breaking change** as it would likely remove the need for the `ScreenDiagsTimer` marker struct, which would mean the current method of enabling & disabling would no longer work.

Happy to work on an implementation of this, @jomala - your call on whether or not this makes sense for the library.

**Comment by SUPERCILEX** [comment]
That's actually how it [used to work](https://github.com/jomala/bevy_screen_diags/pull/1) and the current approach was simpler. Are you suggesting that the library not use a timer at all and instead have users do it?

**Comment by jomala** [comment]
In 0.4.0 (for Bevy 0.7), I've left the option open to control the display in detail as before, but now most users can simply use enable() and disable() - see the example. Hope that provides what you need.
